### Get all songs endpoint
GET http://localhost:3000/songs


### Create a new song endpoint
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title":"Tuzavomayo Ibyiza",
    "artists":["HWT"],
    "releaseDate":"2024-01-01",
    "duration":"02:23"
}



